// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/codepzj/Stellux-Server/conf"
	"github.com/codepzj/Stellux-Server/internal/domain"
	"github.com/codepzj/Stellux-Server/internal/domain/infra"
	"github.com/codepzj/Stellux-Server/internal/server"
	"github.com/codepzj/Stellux-Server/internal/service"
)

// Injectors from wire.go:

// wireApp 初始化应用
func wireApp(confServer *conf.Server, confMysql *conf.Mysql, confLog *conf.Log) (*server.HttpServer, error) {
	db := infra.NewDB(confMysql)
	sugaredLogger := infra.NewLogger(confLog)
	data := domain.NewData(db, sugaredLogger)
	postRepo := domain.NewPostRepo(data, sugaredLogger)
	postService := service.NewPostService(postRepo)
	ginEngine := server.NewGin(postService)
	httpServer := server.NewHttpServer(ginEngine, confServer)
	return httpServer, nil
}
