// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package setting

import (
	"github.com/chenmingyong0423/go-mongox/v2"
	"github.com/codepzj/stellux/server/internal/setting/internal/repository"
	"github.com/codepzj/stellux/server/internal/setting/internal/repository/dao"
	"github.com/codepzj/stellux/server/internal/setting/internal/service"
	"github.com/codepzj/stellux/server/internal/setting/internal/web"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitSettingModule(mongoDB *mongox.Database) *Module {
	settingDao := dao.NewSettingDao(mongoDB)
	settingRepository := repository.NewSettingRepository(settingDao)
	settingService := service.NewSettingService(settingRepository)
	settingHandler := web.NewSettingHandler(settingService)
	module := &Module{
		Svc: settingService,
		Hdl: settingHandler,
	}
	return module
}

// wire.go:

var SettingProviders = wire.NewSet(web.NewSettingHandler, service.NewSettingService, repository.NewSettingRepository, dao.NewSettingDao, wire.Bind(new(service.ISettingService), new(*service.SettingService)), wire.Bind(new(repository.ISettingRepository), new(*repository.SettingRepository)), wire.Bind(new(dao.ISettingDao), new(*dao.SettingDao)))
