// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package file

import (
	"github.com/codepzj/Stellux-Server/internal/file/internal/repository"
	"github.com/codepzj/Stellux-Server/internal/file/internal/repository/dao"
	"github.com/codepzj/Stellux-Server/internal/file/internal/service"
	"github.com/codepzj/Stellux-Server/internal/file/internal/web"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitFileModule(db *gorm.DB) *Module {
	fileDao := dao.NewFileDao(db)
	fileRepository := repository.NewFileRepository(fileDao)
	fileService := service.NewFileService(fileRepository)
	fileHandler := web.NewFileHandler(fileService)
	module := &Module{
		Svc: fileService,
		Hdl: fileHandler,
	}
	return module
}

// wire.go:

var FileProviders = wire.NewSet(web.NewFileHandler, service.NewFileService, repository.NewFileRepository, dao.NewFileDao, wire.Bind(new(service.IFileService), new(*service.FileService)), wire.Bind(new(repository.IFileRepository), new(*repository.FileRepository)), wire.Bind(new(dao.IFileDao), new(*dao.FileDao)))
