MongoDB:
  HOST: "localhost" # 数据库地址
  PORT: 27017 # 数据库端口
  MONGO_INITDB_ROOT_USERNAME: "admin" # 数据库管理员用户名
  MONGO_INITDB_ROOT_PASSWORD: "123456" # 数据库管理员密码
  MONGO_INITDB_DATABASE: "stellux" # 数据库名称
  MONGO_USERNAME: "stellux" # 数据库用户名
  MONGO_PASSWORD: "123456" # 数据库密码

Server:
  PORT: 9001 # 服务端口
  JWT_SECRET: "stellux" # JWT密钥
  Log:
    ENV: "dev" # 环境
    LEVEL: "debug" # 日志级别
    FILE: "log/server_dev.log" # 日志文件
    ERROR_FILE: "log/error_dev.log" # 错误日志文件
    MAX_SIZE: 10 # 日志文件最大大小
    MAX_BACKUPS: 3 # 日志文件最大备份
    MAX_AGE: 30 # 日志文件最大年龄
    COMPRESS: true # 是否压缩日志文件
