mysql:
  dsn: "root:123456@tcp(localhost:23306)/stellux?charset=utf8mb4&parseTime=True&loc=Local"
  log_type: 1 # 0 控制台，1 文件
  log_file: ./logs/mysql.log
  slow_sql_threshold: 1 # 慢查询日志，单位s
  log_level: info # silent/error/warn/info

log:
  level: debug # debug/info/warn/error 日志级别
  full_log_filename: ./logs/server_dev.log # 日志文件名
  error_log_filename: ./logs/server_dev_error.log # 错误日志文件名
  max_size: 10 # 单个日志文件最大尺寸，单位MB
  max_backups: 5 # 最大保留日志文件数量
  max_age: 30 # 最大保留天数
  compress: true # 是否压缩日志文件

server:
  port: 9001 # 服务端口
  jwt_secret: "stellux" # JWT密钥
