// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/codepzj/Stellux-Server/conf"
	"github.com/codepzj/Stellux-Server/internal/document"
	"github.com/codepzj/Stellux-Server/internal/document_content"
	"github.com/codepzj/Stellux-Server/internal/file"
	"github.com/codepzj/Stellux-Server/internal/friend"
	"github.com/codepzj/Stellux-Server/internal/infra"
	"github.com/codepzj/Stellux-Server/internal/ioc"
	"github.com/codepzj/Stellux-Server/internal/label"
	"github.com/codepzj/Stellux-Server/internal/post"
	"github.com/codepzj/Stellux-Server/internal/user"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp(cfg *conf.Config) *HttpServer {
	db := infra.NewPgsql(cfg)
	module := user.InitUserModule(db)
	userHandler := module.Hdl
	database := infra.NewMongoDB(cfg)
	postModule := post.InitPostModule(database)
	postHandler := postModule.Hdl
	labelModule := label.InitLabelModule(database)
	labelHandler := labelModule.Hdl
	fileModule := file.InitFileModule(db)
	fileHandler := fileModule.Hdl
	documentModule := document.InitDocumentModule(database)
	documentHandler := documentModule.Hdl
	document_contentModule := document_content.InitDocumentContentModule(database)
	documentContentHandler := document_contentModule.Hdl
	friendModule := friend.InitFriendModule(database)
	friendHandler := friendModule.Hdl
	v := ioc.InitMiddleWare()
	engine := ioc.NewGin(userHandler, postHandler, labelHandler, fileHandler, documentHandler, documentContentHandler, friendHandler, v)
	httpServer := NewHttpServer(engine, cfg)
	return httpServer
}

// wire.go:

// 基础设施
var InfraProvider = wire.NewSet(infra.NewMongoDB, infra.NewPgsql)

// 控制反转
var IocProvider = wire.NewSet(ioc.InitMiddleWare, ioc.NewGin)
