// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package friend

import (
	"github.com/chenmingyong0423/go-mongox/v2"
	"github.com/codepzj/stellux/server/internal/friend/internal/repository"
	"github.com/codepzj/stellux/server/internal/friend/internal/repository/dao"
	"github.com/codepzj/stellux/server/internal/friend/internal/service"
	"github.com/codepzj/stellux/server/internal/friend/internal/web"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitFriendModule(mongoDB *mongox.Database) *Module {
	friendDao := dao.NewFriendDao(mongoDB)
	friendRepository := repository.NewFriendRepository(friendDao)
	friendService := service.NewFriendService(friendRepository)
	friendHandler := web.NewFriendHandler(friendService)
	module := &Module{
		Svc: friendService,
		Hdl: friendHandler,
	}
	return module
}

// wire.go:

var FriendProviders = wire.NewSet(web.NewFriendHandler, service.NewFriendService, repository.NewFriendRepository, dao.NewFriendDao, wire.Bind(new(service.IFriendService), new(*service.FriendService)), wire.Bind(new(repository.IFriendRepository), new(*repository.FriendRepository)), wire.Bind(new(dao.IFriendDao), new(*dao.FriendDao)))
