// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q               = new(Query)
	Document        *document
	DocumentContent *documentContent
	File            *file
	Friend          *friend
	Post            *post
	PostCategory    *postCategory
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Document = &Q.Document
	DocumentContent = &Q.DocumentContent
	File = &Q.File
	Friend = &Q.Friend
	Post = &Q.Post
	PostCategory = &Q.PostCategory
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		Document:        newDocument(db, opts...),
		DocumentContent: newDocumentContent(db, opts...),
		File:            newFile(db, opts...),
		Friend:          newFriend(db, opts...),
		Post:            newPost(db, opts...),
		PostCategory:    newPostCategory(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Document        document
	DocumentContent documentContent
	File            file
	Friend          friend
	Post            post
	PostCategory    postCategory
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Document:        q.Document.clone(db),
		DocumentContent: q.DocumentContent.clone(db),
		File:            q.File.clone(db),
		Friend:          q.Friend.clone(db),
		Post:            q.Post.clone(db),
		PostCategory:    q.PostCategory.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Document:        q.Document.replaceDB(db),
		DocumentContent: q.DocumentContent.replaceDB(db),
		File:            q.File.replaceDB(db),
		Friend:          q.Friend.replaceDB(db),
		Post:            q.Post.replaceDB(db),
		PostCategory:    q.PostCategory.replaceDB(db),
	}
}

type queryCtx struct {
	Document        IDocumentDo
	DocumentContent IDocumentContentDo
	File            IFileDo
	Friend          IFriendDo
	Post            IPostDo
	PostCategory    IPostCategoryDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Document:        q.Document.WithContext(ctx),
		DocumentContent: q.DocumentContent.WithContext(ctx),
		File:            q.File.WithContext(ctx),
		Friend:          q.Friend.WithContext(ctx),
		Post:            q.Post.WithContext(ctx),
		PostCategory:    q.PostCategory.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
