// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/codepzj/Stellux-Server/internal/domain/model"
)

func newPostCategory(db *gorm.DB, opts ...gen.DOOption) postCategory {
	_postCategory := postCategory{}

	_postCategory.postCategoryDo.UseDB(db, opts...)
	_postCategory.postCategoryDo.UseModel(&model.PostCategory{})

	tableName := _postCategory.postCategoryDo.TableName()
	_postCategory.ALL = field.NewAsterisk(tableName)
	_postCategory.ID = field.NewInt64(tableName, "id")
	_postCategory.CreatedAt = field.NewTime(tableName, "created_at")
	_postCategory.UpdatedAt = field.NewTime(tableName, "updated_at")
	_postCategory.DeletedAt = field.NewField(tableName, "deleted_at")
	_postCategory.CategoryName = field.NewString(tableName, "category_name")

	_postCategory.fillFieldMap()

	return _postCategory
}

// postCategory 文章分类表
type postCategory struct {
	postCategoryDo postCategoryDo

	ALL          field.Asterisk
	ID           field.Int64  // 主键
	CreatedAt    field.Time   // 创建时间
	UpdatedAt    field.Time   // 更新时间
	DeletedAt    field.Field  // 逻辑删除标记
	CategoryName field.String // 分类名称

	fieldMap map[string]field.Expr
}

func (p postCategory) Table(newTableName string) *postCategory {
	p.postCategoryDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p postCategory) As(alias string) *postCategory {
	p.postCategoryDo.DO = *(p.postCategoryDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *postCategory) updateTableName(table string) *postCategory {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")
	p.CategoryName = field.NewString(table, "category_name")

	p.fillFieldMap()

	return p
}

func (p *postCategory) WithContext(ctx context.Context) IPostCategoryDo {
	return p.postCategoryDo.WithContext(ctx)
}

func (p postCategory) TableName() string { return p.postCategoryDo.TableName() }

func (p postCategory) Alias() string { return p.postCategoryDo.Alias() }

func (p postCategory) Columns(cols ...field.Expr) gen.Columns {
	return p.postCategoryDo.Columns(cols...)
}

func (p *postCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *postCategory) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 5)
	p.fieldMap["id"] = p.ID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["category_name"] = p.CategoryName
}

func (p postCategory) clone(db *gorm.DB) postCategory {
	p.postCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p postCategory) replaceDB(db *gorm.DB) postCategory {
	p.postCategoryDo.ReplaceDB(db)
	return p
}

type postCategoryDo struct{ gen.DO }

type IPostCategoryDo interface {
	gen.SubQuery
	Debug() IPostCategoryDo
	WithContext(ctx context.Context) IPostCategoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPostCategoryDo
	WriteDB() IPostCategoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPostCategoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPostCategoryDo
	Not(conds ...gen.Condition) IPostCategoryDo
	Or(conds ...gen.Condition) IPostCategoryDo
	Select(conds ...field.Expr) IPostCategoryDo
	Where(conds ...gen.Condition) IPostCategoryDo
	Order(conds ...field.Expr) IPostCategoryDo
	Distinct(cols ...field.Expr) IPostCategoryDo
	Omit(cols ...field.Expr) IPostCategoryDo
	Join(table schema.Tabler, on ...field.Expr) IPostCategoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPostCategoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPostCategoryDo
	Group(cols ...field.Expr) IPostCategoryDo
	Having(conds ...gen.Condition) IPostCategoryDo
	Limit(limit int) IPostCategoryDo
	Offset(offset int) IPostCategoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPostCategoryDo
	Unscoped() IPostCategoryDo
	Create(values ...*model.PostCategory) error
	CreateInBatches(values []*model.PostCategory, batchSize int) error
	Save(values ...*model.PostCategory) error
	First() (*model.PostCategory, error)
	Take() (*model.PostCategory, error)
	Last() (*model.PostCategory, error)
	Find() ([]*model.PostCategory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PostCategory, err error)
	FindInBatches(result *[]*model.PostCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PostCategory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPostCategoryDo
	Assign(attrs ...field.AssignExpr) IPostCategoryDo
	Joins(fields ...field.RelationField) IPostCategoryDo
	Preload(fields ...field.RelationField) IPostCategoryDo
	FirstOrInit() (*model.PostCategory, error)
	FirstOrCreate() (*model.PostCategory, error)
	FindByPage(offset int, limit int) (result []*model.PostCategory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPostCategoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p postCategoryDo) Debug() IPostCategoryDo {
	return p.withDO(p.DO.Debug())
}

func (p postCategoryDo) WithContext(ctx context.Context) IPostCategoryDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p postCategoryDo) ReadDB() IPostCategoryDo {
	return p.Clauses(dbresolver.Read)
}

func (p postCategoryDo) WriteDB() IPostCategoryDo {
	return p.Clauses(dbresolver.Write)
}

func (p postCategoryDo) Session(config *gorm.Session) IPostCategoryDo {
	return p.withDO(p.DO.Session(config))
}

func (p postCategoryDo) Clauses(conds ...clause.Expression) IPostCategoryDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p postCategoryDo) Returning(value interface{}, columns ...string) IPostCategoryDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p postCategoryDo) Not(conds ...gen.Condition) IPostCategoryDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p postCategoryDo) Or(conds ...gen.Condition) IPostCategoryDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p postCategoryDo) Select(conds ...field.Expr) IPostCategoryDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p postCategoryDo) Where(conds ...gen.Condition) IPostCategoryDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p postCategoryDo) Order(conds ...field.Expr) IPostCategoryDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p postCategoryDo) Distinct(cols ...field.Expr) IPostCategoryDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p postCategoryDo) Omit(cols ...field.Expr) IPostCategoryDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p postCategoryDo) Join(table schema.Tabler, on ...field.Expr) IPostCategoryDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p postCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPostCategoryDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p postCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IPostCategoryDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p postCategoryDo) Group(cols ...field.Expr) IPostCategoryDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p postCategoryDo) Having(conds ...gen.Condition) IPostCategoryDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p postCategoryDo) Limit(limit int) IPostCategoryDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p postCategoryDo) Offset(offset int) IPostCategoryDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p postCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPostCategoryDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p postCategoryDo) Unscoped() IPostCategoryDo {
	return p.withDO(p.DO.Unscoped())
}

func (p postCategoryDo) Create(values ...*model.PostCategory) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p postCategoryDo) CreateInBatches(values []*model.PostCategory, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p postCategoryDo) Save(values ...*model.PostCategory) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p postCategoryDo) First() (*model.PostCategory, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PostCategory), nil
	}
}

func (p postCategoryDo) Take() (*model.PostCategory, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PostCategory), nil
	}
}

func (p postCategoryDo) Last() (*model.PostCategory, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PostCategory), nil
	}
}

func (p postCategoryDo) Find() ([]*model.PostCategory, error) {
	result, err := p.DO.Find()
	return result.([]*model.PostCategory), err
}

func (p postCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PostCategory, err error) {
	buf := make([]*model.PostCategory, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p postCategoryDo) FindInBatches(result *[]*model.PostCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p postCategoryDo) Attrs(attrs ...field.AssignExpr) IPostCategoryDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p postCategoryDo) Assign(attrs ...field.AssignExpr) IPostCategoryDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p postCategoryDo) Joins(fields ...field.RelationField) IPostCategoryDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p postCategoryDo) Preload(fields ...field.RelationField) IPostCategoryDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p postCategoryDo) FirstOrInit() (*model.PostCategory, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PostCategory), nil
	}
}

func (p postCategoryDo) FirstOrCreate() (*model.PostCategory, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PostCategory), nil
	}
}

func (p postCategoryDo) FindByPage(offset int, limit int) (result []*model.PostCategory, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p postCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p postCategoryDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p postCategoryDo) Delete(models ...*model.PostCategory) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *postCategoryDo) withDO(do gen.Dao) *postCategoryDo {
	p.DO = *do.(*gen.DO)
	return p
}
