// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDocumentContent = "document_content"

// DocumentContent 文档内容表
type DocumentContent struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                        // 主键
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;comment:逻辑删除标记" json:"deleted_at"`                                  // 逻辑删除标记
	DocumentID  int64          `gorm:"column:document_id;not null;comment:文档id" json:"document_id"`                         // 文档id
	Title       string         `gorm:"column:title;not null;comment:标题" json:"title"`                                       // 标题
	Content     string         `gorm:"column:content;not null;comment:内容" json:"content"`                                   // 内容
	Description string         `gorm:"column:description;not null;comment:描述" json:"description"`                           // 描述
	Alias_      string         `gorm:"column:alias;not null;comment:别名" json:"alias"`                                       // 别名
	ParentID    int64          `gorm:"column:parent_id;not null;comment:父级id" json:"parent_id"`                             // 父级id
	IsDir       int32          `gorm:"column:is_dir;not null;comment:是否是目录" json:"is_dir"`                                  // 是否是目录
	Sort        int32          `gorm:"column:sort;not null;comment:排序" json:"sort"`                                         // 排序
}

// TableName DocumentContent's table name
func (*DocumentContent) TableName() string {
	return TableNameDocumentContent
}
