// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameFile = "file"

// File 本地文件表
type File struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                        // 主键
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:逻辑删除标记" json:"deleted_at"`                                  // 逻辑删除标记
	FileName  string         `gorm:"column:file_name;not null;comment:文件名称" json:"file_name"`                             // 文件名称
	URL       string         `gorm:"column:url;not null;comment:文件url" json:"url"`                                        // 文件url
	Dst       string         `gorm:"column:dst;not null;comment:文件路径" json:"dst"`                                         // 文件路径
}

// TableName File's table name
func (*File) TableName() string {
	return TableNameFile
}
