// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameFriend = "friend"

// Friend 友情链接表
type Friend struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                        // 主键
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;comment:逻辑删除标记" json:"deleted_at"`                                  // 逻辑删除标记
	Name        string         `gorm:"column:name;not null;comment:名称" json:"name"`                                         // 名称
	Description string         `gorm:"column:description;not null;comment:描述" json:"description"`                           // 描述
	SiteURL     string         `gorm:"column:site_url;not null;comment:站点url" json:"site_url"`                              // 站点url
	AvatarURL   string         `gorm:"column:avatar_url;not null;comment:头像url" json:"avatar_url"`                          // 头像url
	WebsiteType int32          `gorm:"column:website_type;not null;comment:网站类型" json:"website_type"`                       // 网站类型
	IsActive    int32          `gorm:"column:is_active;not null;comment:是否激活" json:"is_active"`                             // 是否激活
}

// TableName Friend's table name
func (*Friend) TableName() string {
	return TableNameFriend
}
