// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePost = "post"

// Post 文章表
type Post struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                        // 主键
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;comment:逻辑删除标记" json:"deleted_at"`                                  // 逻辑删除标记
	Title       string         `gorm:"column:title;not null;comment:标题" json:"title"`                                       // 标题
	Content     string         `gorm:"column:content;not null;comment:内容" json:"content"`                                   // 内容
	Description string         `gorm:"column:description;not null;comment:描述" json:"description"`                           // 描述
	Alias_      string         `gorm:"column:alias;not null;comment:别名" json:"alias"`                                       // 别名
	CategoryID  int64          `gorm:"column:category_id;not null;comment:分类id" json:"category_id"`                         // 分类id
	IsPublish   int32          `gorm:"column:is_publish;not null;comment:是否发布" json:"is_publish"`                           // 是否发布
	IsTop       int32          `gorm:"column:is_top;not null;comment:是否置顶" json:"is_top"`                                   // 是否置顶
	Thumbnail   string         `gorm:"column:thumbnail;not null;comment:缩略图" json:"thumbnail"`                              // 缩略图
}

// TableName Post's table name
func (*Post) TableName() string {
	return TableNamePost
}
