// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package comment

import (
	"github.com/codepzj/Stellux-Server/internal/comment/internal/repository"
	"github.com/codepzj/Stellux-Server/internal/comment/internal/repository/dao"
	"github.com/codepzj/Stellux-Server/internal/comment/internal/service"
	"github.com/codepzj/Stellux-Server/internal/comment/internal/web"
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/v2/mongo"
)

// Injectors from wire.go:

func InitCommentModule(mongoDB *mongo.Database) *Module {
	commentDao := dao.NewCommentDao(mongoDB)
	commentRepository := repository.NewCommentRepository(commentDao)
	commentService := service.NewCommentService(commentRepository)
	commentHandler := web.NewCommentHandler(commentService)
	module := &Module{
		Svc: commentService,
		Hdl: commentHandler,
	}
	return module
}

// wire.go:

var CommentProviders = wire.NewSet(web.NewCommentHandler, service.NewCommentService, repository.NewCommentRepository, dao.NewCommentDao, wire.Bind(new(service.ICommentService), new(*service.CommentService)), wire.Bind(new(repository.ICommentRepository), new(*repository.CommentRepository)), wire.Bind(new(dao.ICommentDao), new(*dao.CommentDao)))
