// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/codepzj/Stellux-Server/internal/config/internal/repository"
	"github.com/codepzj/Stellux-Server/internal/config/internal/repository/dao"
	"github.com/codepzj/Stellux-Server/internal/config/internal/service"
	"github.com/codepzj/Stellux-Server/internal/config/internal/web"
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/v2/mongo"
)

// Injectors from wire.go:

func InitConfigModule(mongoDB *mongo.Database) *Module {
	configDao := dao.NewConfigDao(mongoDB)
	configRepository := repository.NewConfigRepository(configDao)
	configService := service.NewConfigService(configRepository)
	configHandler := web.NewConfigHandler(configService)
	module := &Module{
		Svc: configService,
		Hdl: configHandler,
	}
	return module
}

// wire.go:

var ConfigProviders = wire.NewSet(web.NewConfigHandler, service.NewConfigService, repository.NewConfigRepository, dao.NewConfigDao, wire.Bind(new(service.IConfigService), new(*service.ConfigService)), wire.Bind(new(repository.IConfigRepository), new(*repository.ConfigRepository)), wire.Bind(new(dao.IConfigDao), new(*dao.ConfigDao)))
