// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package post

import (
	"github.com/codepzj/Stellux-Server/internal/post/internal/repository"
	"github.com/codepzj/Stellux-Server/internal/post/internal/repository/dao"
	"github.com/codepzj/Stellux-Server/internal/post/internal/service"
	"github.com/codepzj/Stellux-Server/internal/post/internal/web"
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/v2/mongo"
)

// Injectors from wire.go:

func InitPostModule(mongoDB *mongo.Database) *Module {
	postDao := dao.NewPostDao(mongoDB)
	postRepository := repository.NewPostRepository(postDao)
	postService := service.NewPostService(postRepository)
	postHandler := web.NewPostHandler(postService)
	module := &Module{
		Hdl: postHandler,
	}
	return module
}

// wire.go:

var PostProviders = wire.NewSet(web.NewPostHandler, service.NewPostService, repository.NewPostRepository, dao.NewPostDao, wire.Bind(new(service.IPostService), new(*service.PostService)), wire.Bind(new(repository.IPostRepository), new(*repository.PostRepository)), wire.Bind(new(dao.IPostDao), new(*dao.PostDao)))
